language: ruby
rvm:
  - 1.9.3
before_script:
  - "rake db:migrate jetty:start"
  - "sleep 15"
  - "rake metastore:testdata:index"
script: "rake spec cucumber"

# whitelist
branches:
  only:
    - master
