# TODO commands that need to be run:
# create the db (only the first time)
#docker-compose run web rake db:setup

version: '2'

services:
  solr:
    build: "https://github.com/dtulibrary/solr_with_fixtures.git"

  db:
    image: postgres

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"



