# TODO commands that need to be run:
#docker exec -it --user=solr findit-solr bin/solr create_collection -c metastore
#docker exec -it --user=solr findit-solr bin/solr create_collection -c toc

# And from within the container:
#docker exec --it findit-solr bash
#bin/post -c metastore /fixtures/solr_data.xml
#bin/post -c toc /fixtures/toc_data.xml

# create the db (only the first time)
#docker-compose run findit-web bundle exec rake db:migrate

findit-solr:
  image: solr:5.3
  container_name: findit-solr
  volumes:
    - "./spec/fixtures:/fixtures"
    - "./controller/src/main/resources/solr:/config"
  ports:
    - "8983:8983"
  command: "/opt/solr/bin/solr -f -c"

findit-db:
  image: postgres

findit-web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - findit-db
    - findit-solr



